# Generated by Django 6.0 on 2025-12-09 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, verbose_name='公司名稱')),
                ('tax_id', models.CharField(max_length=20, unique=True, verbose_name='統一編號')),
                ('contact_person', models.CharField(blank=True, max_length=50, null=True, verbose_name='聯絡人')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='電話')),
            ],
            options={
                'verbose_name': '雇主',
                'verbose_name_plural': '雇主',
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arc_number', models.CharField(max_length=20, unique=True, verbose_name='居留證號')),
                ('passport_number', models.CharField(max_length=20, verbose_name='護照號碼')),
                ('full_name', models.CharField(max_length=100, verbose_name='移工全名')),
                ('nationality', models.CharField(max_length=50, verbose_name='國籍')),
                ('hire_date', models.DateField(verbose_name='僱用起始日期')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否在職')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='compliance.employer', verbose_name='所屬雇主')),
            ],
            options={
                'verbose_name': '移工',
                'verbose_name_plural': '移工',
            },
        ),
        migrations.CreateModel(
            name='MedicalExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateField(verbose_name='實際體檢日期')),
                ('exam_type', models.CharField(choices=[('入境體檢', '入境體檢'), ('6個月體檢', '6個月體檢'), ('18個月體檢', '18個月體檢'), ('30個月體檢', '30個月體檢'), ('其他', '其他')], max_length=20, verbose_name='體檢類別')),
                ('report_status', models.CharField(choices=[('合格', '合格'), ('不合格', '不合格'), ('補檢中', '補檢中'), ('待審核', '待審核'), ('已完成', '已完成')], max_length=20, verbose_name='報告狀態')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='體檢有效期限')),
                ('hospital_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='醫院名稱')),
                ('report_document_url', models.TextField(blank=True, null=True, verbose_name='報告文件URL')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compliance.worker', verbose_name='移工')),
            ],
            options={
                'verbose_name': '體檢紀錄',
                'verbose_name_plural': '體檢紀錄',
                'unique_together': {('worker', 'exam_type', 'exam_date')},
            },
        ),
    ]
